(defun dired-search (dir regexp)
  ""
  (interactive "DSearch in the directory: \nsRegexp:")
  (setq directory-list (list dir))
  (setq result (list))
  (while (not (equal directory-list nil))
    (setq d (car directory-list))
    (setq directory-list (cdr directory-list))
    (dolist (file (directory-files d))
      (let ((f (concat d "/" file)))
        (unless (or (member file '("." ".."))
                    (string= (substring file 0 1) "."))
          (if (file-directory-p f)
              (setq directory-list (add-to-list 'directory-list f t))
            (when (string-match regexp file)
              (if (equal result nil)
                  (push f result)
                (add-to-list 'result f t))))))))
  (if (equal (length result) 0)
      (message "No file does not exist or is invisible.")
    (dired (cons dir result))))

(provide 'dired-search)
